// Build-time asset generator for Country.region (see data/types.ts's own
// doc comment: "Broad grouping for filtering/legends in a future layer...
// deliberately a plain string" — this is that future layer, feeding the
// News tab's region-hub filter, hud/NewsPanel.tsx).
//
// Standalone data-generation script only — does NOT touch GeoEntity/Country
// type definitions, registries, or any rendering/UI code.
//
// SOURCING — World Bank's own country classification
// (https://api.worldbank.org/v2/country?format=json&per_page=300), the
// same API this project's buildEconomy.mjs/buildGovCapitalPopGdp.mjs
// already cite. One bulk fetch returns every country/aggregate World Bank
// tracks, each with a real `region: {id, iso2code, value}` field (e.g.
// "North America" for USA) — a citable, already-established-precedent
// source, not an invented taxonomy. World Bank's own real 7-region
// breakdown is used as-is (East Asia & Pacific, Europe & Central Asia,
// Latin America & Caribbean, Middle East & North Africa, North America,
// South Asia, Sub-Saharan Africa) rather than approximating any other
// site's regional scheme.
//
// Kept as its OWN generated file (src/data/countryRegions.ts), deliberately
// NOT folded into buildGovCapitalPopGdp.mjs/countryEconomics.ts — region is
// a single independent per-country lookup with none of that script's
// per-indicator lookback-year complexity; touching that large, already-
// tuned script for this one field would be needless risk for no benefit.
//
// Usage:
//   node scripts/buildCountryRegions.mjs
//     Writes src/data/countryRegions.ts and appends a generated gap report
//     to BACKLOG.md.
//
// Run via `node`, not `tsx` — no existing .ts source needs importing (same
// rule buildEconomy.mjs's header states explicitly).
import fs from 'node:fs'
import { feature } from 'topojson-client'
import { ALPHA3_TO_NUMERIC } from './lib/iso3166.mjs'

const COUNTRIES_SOURCE = 'public/geo/countries-un193.json'
const OUTPUT = 'src/data/countryRegions.ts'
const BACKLOG = 'BACKLOG.md'
const WORLD_BANK_COUNTRY_LIST_URL = 'https://api.worldbank.org/v2/country?format=json&per_page=300'

const topology = JSON.parse(fs.readFileSync(COUNTRIES_SOURCE, 'utf8'))
const allCountries = feature(topology, topology.objects.countries).features.map((f) => ({
  id: String(f.id),
  name: f.properties.name,
}))
// First-occurrence-wins, not last-write-wins: ALPHA3_TO_NUMERIC deliberately
// aliases a couple of non-standard codes to a real numeric id (e.g. "SDS",
// Natural Earth's own non-ISO admin-1 tag for South Sudan, aliased to the
// same numeric id as the canonical "SSD" — see that file's own comment).
// Inverting naively would let a later non-standard alias silently overwrite
// the canonical alpha-3 a real API like World Bank's actually recognizes.
const NUMERIC_TO_ALPHA3 = {}
for (const [a3, num] of Object.entries(ALPHA3_TO_NUMERIC)) {
  if (!(num in NUMERIC_TO_ALPHA3)) NUMERIC_TO_ALPHA3[num] = a3
}

const res = await fetch(WORLD_BANK_COUNTRY_LIST_URL)
if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${WORLD_BANK_COUNTRY_LIST_URL}`)
const [, wbCountries] = await res.json()
// World Bank's own id field IS the ISO alpha-3 code — no name matching
// needed, unlike a source with no code field at all. `.trim()` guards a
// real API quirk confirmed on South Sudan's own record, which comes back
// as "Sub-Saharan Africa " with a trailing space.
const REGION_BY_ALPHA3 = Object.fromEntries(
  wbCountries
    .filter((c) => c.region?.value && c.region.value.trim() !== 'Aggregates')
    .map((c) => [c.id, c.region.value.trim()])
)

const gaps = []
const regions = {}
for (const country of allCountries) {
  const alpha3 = NUMERIC_TO_ALPHA3[country.id]
  const region = alpha3 ? REGION_BY_ALPHA3[alpha3] : undefined
  if (region) {
    regions[country.id] = region
  } else {
    gaps.push({ id: country.id, name: country.name, reason: alpha3 ? 'no World Bank region entry' : 'no alpha-3 code found' })
  }
}

const header = `// Country.region data, generated by scripts/buildCountryRegions.mjs
// (\`npm run build:regions\`) — see that script's own header comment for the
// full World Bank sourcing.
//
// Keyed by the SAME numeric ISO topology id scene/useCountryFeatures.ts
// registers Country records under — same convention as
// src/data/countryEconomics.ts. A country absent from this map has no
// World Bank region classification (see BACKLOG.md's "Data sourcing"
// section) — Country.region is simply left undefined for it, never guessed.
//
// Re-run the build script (rather than hand-editing this file) to refresh.

// World Bank's own 7-region breakdown — a closed set as of this data's own
// source, not a union this project invented. Verified against the live API
// response directly (not assumed) — World Bank's MENA region is currently
// named "Middle East, North Africa, Afghanistan & Pakistan", reflecting
// their own reclassification of Afghanistan/Pakistan out of South Asia.
export type CountryRegion =
  | 'East Asia & Pacific'
  | 'Europe & Central Asia'
  | 'Latin America & Caribbean'
  | 'Middle East, North Africa, Afghanistan & Pakistan'
  | 'North America'
  | 'South Asia'
  | 'Sub-Saharan Africa'

// Keyed by numeric ISO topology id (e.g. "840" for the United States).
export const COUNTRY_REGIONS: Record<string, CountryRegion> = {
`

const body = Object.entries(regions)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, region]) => `  ${JSON.stringify(id)}: ${JSON.stringify(region)},`)
  .join('\n')

const footer = `}\n`

fs.writeFileSync(OUTPUT, header + body + '\n' + footer)
console.log(`Wrote ${OUTPUT}: ${Object.keys(regions).length}/${allCountries.length} countries.`)
console.log(`${gaps.length} gap(s) logged.`)

function writeBacklogReport() {
  const BEGIN = '<!-- BEGIN buildCountryRegions.mjs gap report -->'
  const END = '<!-- END buildCountryRegions.mjs gap report -->'
  const generatedAt = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(BEGIN)
  lines.push('')
  lines.push(
    `**Generated by \`npm run build:regions\` (\`scripts/buildCountryRegions.mjs\`), ${generatedAt}.** ` +
      `Countries with no World Bank region classification this run. Re-running the script regenerates this list.`
  )
  lines.push('')
  if (gaps.length === 0) {
    lines.push('- None this run — every country resolved a region.')
  } else {
    for (const g of gaps.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- **${g.name}:** ${g.reason}`)
    }
  }
  lines.push('')
  lines.push(END)
  const section = lines.join('\n')

  const backlog = fs.readFileSync(BACKLOG, 'utf8')
  const beginIdx = backlog.indexOf(BEGIN)
  const endIdx = backlog.indexOf(END)
  let updated
  if (beginIdx !== -1 && endIdx !== -1) {
    updated = backlog.slice(0, beginIdx) + section + backlog.slice(endIdx + END.length)
  } else {
    const heading = '\n## Data sourcing (`buildCountryRegions.mjs`)\n\n'
    const introEnd = backlog.indexOf('\n## ')
    updated =
      introEnd === -1
        ? backlog + heading + section + '\n'
        : backlog.slice(0, introEnd) + heading + section + '\n' + backlog.slice(introEnd)
  }
  fs.writeFileSync(BACKLOG, updated)
  console.log(`Updated ${BACKLOG}: ${gaps.length} gap(s) logged.`)
}

writeBacklogReport()
