// Current Status category data for the Intelligence Engine, generated by
// scripts/buildCurrentStatus.mjs (`npm run build:current-status`) per the
// locked design in Intelligence Docs/intelligence-engine-scoring-design.md
// §3.5 — see that script's own header comment for the full UCDP sourcing
// and matching logic.
//
// NOT a 0-100 score, unlike Military/Economy — two independent, categorical
// fields per country. Absence (no conflict, no active OFAC program) is a
// real, positive fact and is always serialized explicitly (conflicts: [],
// sanctionTier: null), never omitted.
//
// Keyed by the SAME numeric ISO topology id scene/useCountryFeatures.ts
// registers Country records under (String(feature.id) from
// countries-un193.json) — same convention as src/data/militaryScores.ts /
// src/data/economyScores.ts.
//
// Re-run the build script (rather than hand-editing this file) to refresh.

export type ConflictType =
  | 'interstate'
  | 'internal'
  | 'internationalized_internal'
  | 'extrasystemic'
  | 'unclassified'

export interface ConflictEntry {
  conflictType: ConflictType
  conflictName?: string
  /** Which UCDP source release this reflects (a version identifier, not a calendar date). */
  snapshotDate: string
  source: 'ucdp-candidate' | 'ucdp-prio-annual'
}

// See this script's own header comment for the tier definitions and the
// BACKLOG.md flag on ORANGE/YELLOW confidence.
export type SanctionTier = 'red' | 'orange' | 'yellow' | null

export interface CurrentStatus {
  name: string
  /** 0, 1, or many — every entry renders as its own chip. */
  conflicts: ConflictEntry[]
  /** null = no active OFAC country program — badge hidden, not a data gap. */
  sanctionTier: SanctionTier
  /** The actual OFAC program name(s), e.g. ['Cuba Sanctions']. Present iff sanctionTier isn't null. */
  sanctionPrograms?: string[]
}

// Keyed by numeric ISO topology id (e.g. "840" for the United States).
export const CURRENT_STATUS: Record<string, CurrentStatus> = {
  "004": {
    name: "Afghanistan",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Afghanistan vs. NRF", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Afghanistan vs. Government of Pakistan", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Afghanistan vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Afghanistan-Related Sanctions"],
  },
  "008": {
    name: "Albania",
    conflicts: [],
    sanctionTier: null,
  },
  "012": {
    name: "Algeria",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Algeria: Government", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "020": {
    name: "Andorra",
    conflicts: [],
    sanctionTier: null,
  },
  "024": {
    name: "Angola",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Angola vs. FLEC-FAC-TN", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "028": {
    name: "Antigua and Barbuda",
    conflicts: [],
    sanctionTier: null,
  },
  "032": {
    name: "Argentina",
    conflicts: [],
    sanctionTier: null,
  },
  "051": {
    name: "Armenia",
    conflicts: [],
    sanctionTier: null,
  },
  "036": {
    name: "Australia",
    conflicts: [],
    sanctionTier: null,
  },
  "040": {
    name: "Austria",
    conflicts: [],
    sanctionTier: null,
  },
  "031": {
    name: "Azerbaijan",
    conflicts: [],
    sanctionTier: null,
  },
  "044": {
    name: "Bahamas",
    conflicts: [],
    sanctionTier: null,
  },
  "048": {
    name: "Bahrain",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "050": {
    name: "Bangladesh",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Bangladesh: Chittagong Hill Tracts", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Bangladesh - Myanmar (Burma)", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "052": {
    name: "Barbados",
    conflicts: [],
    sanctionTier: null,
  },
  "112": {
    name: "Belarus",
    conflicts: [],
    sanctionTier: "orange",
    sanctionPrograms: ["Belarus Sanctions"],
  },
  "056": {
    name: "Belgium",
    conflicts: [],
    sanctionTier: null,
  },
  "084": {
    name: "Belize",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "204": {
    name: "Benin",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Benin vs. JNIM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "064": {
    name: "Bhutan",
    conflicts: [],
    sanctionTier: null,
  },
  "068": {
    name: "Bolivia",
    conflicts: [],
    sanctionTier: null,
  },
  "070": {
    name: "Bosnia and Herzegovina",
    conflicts: [],
    sanctionTier: null,
  },
  "072": {
    name: "Botswana",
    conflicts: [],
    sanctionTier: null,
  },
  "076": {
    name: "Brazil",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "096": {
    name: "Brunei",
    conflicts: [],
    sanctionTier: null,
  },
  "100": {
    name: "Bulgaria",
    conflicts: [],
    sanctionTier: null,
  },
  "854": {
    name: "Burkina Faso",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Burkina Faso vs. JNIM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Burkina Faso vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "108": {
    name: "Burundi",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "132": {
    name: "Cabo Verde",
    conflicts: [],
    sanctionTier: null,
  },
  "116": {
    name: "Cambodia",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of Cambodia (Kampuchea) vs. Government of Thailand", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "120": {
    name: "Cameroon",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Cameroon vs. JAS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Cameroon vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Cameroon vs. Ambazonia insurgents", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "124": {
    name: "Canada",
    conflicts: [],
    sanctionTier: null,
  },
  "140": {
    name: "Central African Republic",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Central African Republic vs. CMSPR, CPC, CPC-F", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Central African Republic Sanctions"],
  },
  "148": {
    name: "Chad",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Chad: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "152": {
    name: "Chile",
    conflicts: [],
    sanctionTier: null,
  },
  "156": {
    name: "China",
    conflicts: [],
    sanctionTier: null,
  },
  "170": {
    name: "Colombia",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Colombia vs. ELN, EMBF, FARC-EMC", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "174": {
    name: "Comoros",
    conflicts: [],
    sanctionTier: null,
  },
  "178": {
    name: "Congo",
    conflicts: [],
    sanctionTier: null,
  },
  "188": {
    name: "Costa Rica",
    conflicts: [],
    sanctionTier: null,
  },
  "384": {
    name: "Côte d'Ivoire",
    conflicts: [],
    sanctionTier: null,
  },
  "191": {
    name: "Croatia",
    conflicts: [],
    sanctionTier: null,
  },
  "192": {
    name: "Cuba",
    conflicts: [],
    sanctionTier: "red",
    sanctionPrograms: ["Cuba Sanctions"],
  },
  "196": {
    name: "Cyprus",
    conflicts: [],
    sanctionTier: null,
  },
  "203": {
    name: "Czechia",
    conflicts: [],
    sanctionTier: null,
  },
  "180": {
    name: "Democratic Republic of the Congo",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of DR Congo (Zaire) vs. AFC, CRP", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of DR Congo (Zaire) vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "DR Congo (Zaire) - Rwanda", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internationalized_internal", conflictName: "DR Congo (Zaire): Katanga", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Democratic Republic of the Congo-Related Sanctions"],
  },
  "208": {
    name: "Denmark",
    conflicts: [],
    sanctionTier: null,
  },
  "262": {
    name: "Djibouti",
    conflicts: [
      { conflictType: "internal", conflictName: "Djibouti: Government", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "212": {
    name: "Dominica",
    conflicts: [],
    sanctionTier: null,
  },
  "214": {
    name: "Dominican Republic",
    conflicts: [],
    sanctionTier: null,
  },
  "218": {
    name: "Ecuador",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "818": {
    name: "Egypt",
    conflicts: [],
    sanctionTier: null,
  },
  "222": {
    name: "El Salvador",
    conflicts: [],
    sanctionTier: null,
  },
  "226": {
    name: "Equatorial Guinea",
    conflicts: [],
    sanctionTier: null,
  },
  "232": {
    name: "Eritrea",
    conflicts: [],
    sanctionTier: null,
  },
  "233": {
    name: "Estonia",
    conflicts: [],
    sanctionTier: null,
  },
  "748": {
    name: "Eswatini",
    conflicts: [],
    sanctionTier: null,
  },
  "231": {
    name: "Ethiopia",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Ethiopia vs. OLA", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Ethiopia vs. Fano", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internationalized_internal", conflictName: "Ethiopia: Government", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Ethiopia: Agew", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Ethiopia: Benishangul-Gumuz", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Ethiopia-Related Sanctions"],
  },
  "242": {
    name: "Fiji",
    conflicts: [],
    sanctionTier: null,
  },
  "246": {
    name: "Finland",
    conflicts: [],
    sanctionTier: null,
  },
  "250": {
    name: "France",
    conflicts: [],
    sanctionTier: null,
  },
  "266": {
    name: "Gabon",
    conflicts: [],
    sanctionTier: null,
  },
  "270": {
    name: "Gambia",
    conflicts: [],
    sanctionTier: null,
  },
  "268": {
    name: "Georgia",
    conflicts: [],
    sanctionTier: null,
  },
  "276": {
    name: "Germany",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "288": {
    name: "Ghana",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "300": {
    name: "Greece",
    conflicts: [],
    sanctionTier: null,
  },
  "308": {
    name: "Grenada",
    conflicts: [],
    sanctionTier: null,
  },
  "320": {
    name: "Guatemala",
    conflicts: [],
    sanctionTier: null,
  },
  "324": {
    name: "Guinea",
    conflicts: [],
    sanctionTier: null,
  },
  "624": {
    name: "Guinea-Bissau",
    conflicts: [],
    sanctionTier: null,
  },
  "328": {
    name: "Guyana",
    conflicts: [],
    sanctionTier: null,
  },
  "332": {
    name: "Haiti",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Haiti vs. Viv Ansanm", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "340": {
    name: "Honduras",
    conflicts: [],
    sanctionTier: null,
  },
  "348": {
    name: "Hungary",
    conflicts: [],
    sanctionTier: null,
  },
  "352": {
    name: "Iceland",
    conflicts: [],
    sanctionTier: null,
  },
  "356": {
    name: "India",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of India vs. Government of Pakistan", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of India vs. CPI-Maoist", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of India vs. Kashmir insurgents", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of India vs. UNLFW", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "India: Nagaland", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "India: Manipur", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "360": {
    name: "Indonesia",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Indonesia vs. OPM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "364": {
    name: "Iran",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Iran vs. Jaish al-Adl", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Iran vs. Government of Israel", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Iran: Kurdistan", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Iran: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "red",
    sanctionPrograms: ["Iran Sanctions"],
  },
  "368": {
    name: "Iraq",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Iraq vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Iran: Kurdistan", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "interstate", conflictName: "Iran - Iraq", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Iraq Stabilization and Insurgency Sanctions"],
  },
  "372": {
    name: "Ireland",
    conflicts: [],
    sanctionTier: null,
  },
  "376": {
    name: "Israel",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Israel vs. Hamas, Palestinian Mujahideen Movement, PIJ, PRC", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Israel vs. Government of Syria", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Israel vs. Hezbollah", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Iran vs. Government of Israel", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Israel vs. Government of Yemen (North Yemen)", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "380": {
    name: "Italy",
    conflicts: [],
    sanctionTier: null,
  },
  "388": {
    name: "Jamaica",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "392": {
    name: "Japan",
    conflicts: [],
    sanctionTier: null,
  },
  "400": {
    name: "Jordan",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "398": {
    name: "Kazakhstan",
    conflicts: [],
    sanctionTier: null,
  },
  "404": {
    name: "Kenya",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Kenya vs. Al-Shabaab", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "296": {
    name: "Kiribati",
    conflicts: [],
    sanctionTier: null,
  },
  "414": {
    name: "Kuwait",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "417": {
    name: "Kyrgyzstan",
    conflicts: [],
    sanctionTier: null,
  },
  "418": {
    name: "Laos",
    conflicts: [],
    sanctionTier: null,
  },
  "428": {
    name: "Latvia",
    conflicts: [],
    sanctionTier: null,
  },
  "422": {
    name: "Lebanon",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Lebanon-Related Sanctions"],
  },
  "426": {
    name: "Lesotho",
    conflicts: [],
    sanctionTier: null,
  },
  "430": {
    name: "Liberia",
    conflicts: [],
    sanctionTier: null,
  },
  "434": {
    name: "Libya",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Libya Sanctions"],
  },
  "438": {
    name: "Liechtenstein",
    conflicts: [],
    sanctionTier: null,
  },
  "440": {
    name: "Lithuania",
    conflicts: [],
    sanctionTier: null,
  },
  "442": {
    name: "Luxembourg",
    conflicts: [],
    sanctionTier: null,
  },
  "450": {
    name: "Madagascar",
    conflicts: [],
    sanctionTier: null,
  },
  "454": {
    name: "Malawi",
    conflicts: [],
    sanctionTier: null,
  },
  "458": {
    name: "Malaysia",
    conflicts: [],
    sanctionTier: null,
  },
  "462": {
    name: "Maldives",
    conflicts: [],
    sanctionTier: null,
  },
  "466": {
    name: "Mali",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Mali vs. JNIM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Mali vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Mali vs. FLA", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Mali-Related Sanctions"],
  },
  "470": {
    name: "Malta",
    conflicts: [],
    sanctionTier: null,
  },
  "584": {
    name: "Marshall Islands",
    conflicts: [],
    sanctionTier: null,
  },
  "478": {
    name: "Mauritania",
    conflicts: [],
    sanctionTier: null,
  },
  "480": {
    name: "Mauritius",
    conflicts: [],
    sanctionTier: null,
  },
  "484": {
    name: "Mexico",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "583": {
    name: "Micronesia",
    conflicts: [],
    sanctionTier: null,
  },
  "498": {
    name: "Moldova",
    conflicts: [],
    sanctionTier: null,
  },
  "492": {
    name: "Monaco",
    conflicts: [],
    sanctionTier: null,
  },
  "496": {
    name: "Mongolia",
    conflicts: [],
    sanctionTier: null,
  },
  "499": {
    name: "Montenegro",
    conflicts: [],
    sanctionTier: null,
  },
  "504": {
    name: "Morocco",
    conflicts: [
      { conflictType: "internal", conflictName: "Morocco: Sahrawi Arab Democratic Republic (Western Sahara)", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "508": {
    name: "Mozambique",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Mozambique vs. Naparama", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Mozambique vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "104": {
    name: "Myanmar",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Myanmar (Burma) vs. KNU", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Myanmar (Burma) vs. NUG, PSLF", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Myanmar (Burma) vs. ULA", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Myanmar (Burma) vs. KIO", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Myanmar (Burma) vs. KNPP", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "orange",
    sanctionPrograms: ["Burma-Related Sanctions"],
  },
  "516": {
    name: "Namibia",
    conflicts: [],
    sanctionTier: null,
  },
  "520": {
    name: "Nauru",
    conflicts: [],
    sanctionTier: null,
  },
  "524": {
    name: "Nepal",
    conflicts: [],
    sanctionTier: null,
  },
  "528": {
    name: "Netherlands",
    conflicts: [],
    sanctionTier: null,
  },
  "554": {
    name: "New Zealand",
    conflicts: [],
    sanctionTier: null,
  },
  "558": {
    name: "Nicaragua",
    conflicts: [],
    sanctionTier: "orange",
    sanctionPrograms: ["Nicaragua-Related Sanctions"],
  },
  "562": {
    name: "Niger",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Niger vs. JNIM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Niger vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "566": {
    name: "Nigeria",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Nigeria vs. JAS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Nigeria vs. IPOB", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Nigeria vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "408": {
    name: "North Korea",
    conflicts: [],
    sanctionTier: "red",
    sanctionPrograms: ["North Korea Sanctions"],
  },
  "807": {
    name: "North Macedonia",
    conflicts: [],
    sanctionTier: null,
  },
  "578": {
    name: "Norway",
    conflicts: [],
    sanctionTier: null,
  },
  "512": {
    name: "Oman",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "586": {
    name: "Pakistan",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of India vs. Government of Pakistan", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Pakistan vs. BRAS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Pakistan vs. HGB, IMP, TTP", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Afghanistan vs. Government of Pakistan", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Pakistan vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Pakistan: Sindh", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "585": {
    name: "Palau",
    conflicts: [],
    sanctionTier: null,
  },
  "591": {
    name: "Panama",
    conflicts: [],
    sanctionTier: null,
  },
  "598": {
    name: "Papua New Guinea",
    conflicts: [],
    sanctionTier: null,
  },
  "600": {
    name: "Paraguay",
    conflicts: [],
    sanctionTier: null,
  },
  "604": {
    name: "Peru",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "608": {
    name: "Philippines",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Philippines vs. CPP", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Philippines: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "616": {
    name: "Poland",
    conflicts: [],
    sanctionTier: null,
  },
  "620": {
    name: "Portugal",
    conflicts: [],
    sanctionTier: null,
  },
  "634": {
    name: "Qatar",
    conflicts: [],
    sanctionTier: null,
  },
  "642": {
    name: "Romania",
    conflicts: [],
    sanctionTier: null,
  },
  "643": {
    name: "Russia",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of Russia (Soviet Union) vs. Government of Ukraine", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Russia: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "internal", conflictName: "Russia (Soviet Union): Government", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "orange",
    sanctionPrograms: ["Russian Harmful Foreign Activities Sanctions"],
  },
  "646": {
    name: "Rwanda",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Rwanda vs. FDLR-FOCA", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "659": {
    name: "Saint Kitts and Nevis",
    conflicts: [],
    sanctionTier: null,
  },
  "662": {
    name: "Saint Lucia",
    conflicts: [],
    sanctionTier: null,
  },
  "670": {
    name: "Saint Vincent and the Grenadines",
    conflicts: [],
    sanctionTier: null,
  },
  "882": {
    name: "Samoa",
    conflicts: [],
    sanctionTier: null,
  },
  "674": {
    name: "San Marino",
    conflicts: [],
    sanctionTier: null,
  },
  "678": {
    name: "Sao Tome and Principe",
    conflicts: [],
    sanctionTier: null,
  },
  "682": {
    name: "Saudi Arabia",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "686": {
    name: "Senegal",
    conflicts: [],
    sanctionTier: null,
  },
  "688": {
    name: "Serbia",
    conflicts: [],
    sanctionTier: null,
  },
  "690": {
    name: "Seychelles",
    conflicts: [],
    sanctionTier: null,
  },
  "694": {
    name: "Sierra Leone",
    conflicts: [],
    sanctionTier: null,
  },
  "702": {
    name: "Singapore",
    conflicts: [],
    sanctionTier: null,
  },
  "703": {
    name: "Slovakia",
    conflicts: [],
    sanctionTier: null,
  },
  "705": {
    name: "Slovenia",
    conflicts: [],
    sanctionTier: null,
  },
  "090": {
    name: "Solomon Islands",
    conflicts: [],
    sanctionTier: null,
  },
  "706": {
    name: "Somalia",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Somalia vs. Al-Shabaab", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Somalia vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Somalia Sanctions"],
  },
  "710": {
    name: "South Africa",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "410": {
    name: "South Korea",
    conflicts: [],
    sanctionTier: null,
  },
  "728": {
    name: "South Sudan",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of South Sudan vs. SPLM/A - IO", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["South Sudan-Related Sanctions"],
  },
  "724": {
    name: "Spain",
    conflicts: [],
    sanctionTier: null,
  },
  "144": {
    name: "Sri Lanka",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "729": {
    name: "Sudan",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Sudan vs. RSF, SFA, SPLM/A-North", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: "orange",
    sanctionPrograms: ["Sudan-Related Sanctions"],
  },
  "740": {
    name: "Suriname",
    conflicts: [],
    sanctionTier: null,
  },
  "752": {
    name: "Sweden",
    conflicts: [],
    sanctionTier: null,
  },
  "756": {
    name: "Switzerland",
    conflicts: [],
    sanctionTier: null,
  },
  "760": {
    name: "Syria",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Syria vs. Military Council for the Liberation of Syria", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Israel vs. Government of Syria", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Syria vs. IS", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internationalized_internal", conflictName: "Government of Syria vs. SDF", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Syria: Suweida", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "red",
    sanctionPrograms: ["Syria Sanctions"],
  },
  "762": {
    name: "Tajikistan",
    conflicts: [],
    sanctionTier: null,
  },
  "834": {
    name: "Tanzania",
    conflicts: [],
    sanctionTier: null,
  },
  "764": {
    name: "Thailand",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of Cambodia (Kampuchea) vs. Government of Thailand", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Thailand vs. Patani insurgents", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "626": {
    name: "Timor-Leste",
    conflicts: [],
    sanctionTier: null,
  },
  "768": {
    name: "Togo",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Togo vs. JNIM", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "776": {
    name: "Tonga",
    conflicts: [],
    sanctionTier: null,
  },
  "780": {
    name: "Trinidad and Tobago",
    conflicts: [],
    sanctionTier: null,
  },
  "788": {
    name: "Tunisia",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "792": {
    name: "Turkey",
    conflicts: [
      { conflictType: "internal", conflictName: "Government of Turkey vs. PKK", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Turkey: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", conflictName: "Israel: Islamic State", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "795": {
    name: "Turkmenistan",
    conflicts: [],
    sanctionTier: null,
  },
  "798": {
    name: "Tuvalu",
    conflicts: [],
    sanctionTier: null,
  },
  "800": {
    name: "Uganda",
    conflicts: [],
    sanctionTier: null,
  },
  "804": {
    name: "Ukraine",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of Russia (Soviet Union) vs. Government of Ukraine", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "784": {
    name: "United Arab Emirates",
    conflicts: [
      { conflictType: "unclassified", conflictName: "Iran - Israel, United States of America", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: null,
  },
  "826": {
    name: "United Kingdom",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of United Kingdom, Government of United States of America vs. Government of Yemen (North Yemen)", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "840": {
    name: "United States of America",
    conflicts: [
      { conflictType: "interstate", conflictName: "Government of United Kingdom, Government of United States of America vs. Government of Yemen (North Yemen)", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
    ],
    sanctionTier: null,
  },
  "858": {
    name: "Uruguay",
    conflicts: [],
    sanctionTier: null,
  },
  "860": {
    name: "Uzbekistan",
    conflicts: [],
    sanctionTier: null,
  },
  "548": {
    name: "Vanuatu",
    conflicts: [],
    sanctionTier: null,
  },
  "862": {
    name: "Venezuela",
    conflicts: [
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "orange",
    sanctionPrograms: ["Venezuela-Related Sanctions"],
  },
  "704": {
    name: "Vietnam",
    conflicts: [],
    sanctionTier: null,
  },
  "887": {
    name: "Yemen",
    conflicts: [
      { conflictType: "internationalized_internal", conflictName: "Government of Yemen (North Yemen) vs. Forces of the Presidential Leadership Council", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "internal", conflictName: "Government of Yemen (North Yemen) vs. STC", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of United Kingdom, Government of United States of America vs. Government of Yemen (North Yemen)", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "interstate", conflictName: "Government of Israel vs. Government of Yemen (North Yemen)", snapshotDate: "UCDP/PRIO ACD v26.1", source: "ucdp-prio-annual" },
      { conflictType: "unclassified", snapshotDate: "UCDP Candidate v26.0.7 (Jan-Jul 2026)", source: "ucdp-candidate" },
    ],
    sanctionTier: "yellow",
    sanctionPrograms: ["Yemen-Related Sanctions"],
  },
  "894": {
    name: "Zambia",
    conflicts: [],
    sanctionTier: null,
  },
  "716": {
    name: "Zimbabwe",
    conflicts: [],
    sanctionTier: null,
  },
}
